#!/usr/bin/env node
// server.js — MCP server for claude-mindmap
// Auto-starts shared-server.js if not running, then relays all state via HTTP.

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { exec, spawn } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PORT = parseInt(process.env.MINDMAP_PORT || '3333');
const BASE = `http://localhost:${PORT}`;
const SESSION_ID = randomUUID();

// ── Shared server bootstrap ───────────────────────────────────

async function ping() {
  try { const r = await fetch(`${BASE}/api/ping`); return r.ok; } catch { return false; }
}

async function ensureSharedServer() {
  if (await ping()) return;

  const child = spawn(process.execPath, [join(__dirname, 'shared-server.js')], {
    detached: true,
    stdio: 'ignore',
    env: { ...process.env }
  });
  child.unref();

  for (let i = 0; i < 20; i++) {
    await new Promise(r => setTimeout(r, 250));
    if (await ping()) return;
  }
  console.error('[claude-mindmap] Warning: shared server did not start in time');
}

async function api(method, path, body) {
  try {
    const r = await fetch(`${BASE}${path}`, {
      method,
      headers: body ? { 'Content-Type': 'application/json' } : {},
      body: body ? JSON.stringify(body) : undefined
    });
    return r.ok;
  } catch (e) {
    console.error(`[claude-mindmap] API error ${path}: ${e.message}`);
    return false;
  }
}

// ── Init ──────────────────────────────────────────────────────

await ensureSharedServer();
await api('POST', '/api/sessions', { sessionId: SESSION_ID, pid: process.pid });

async function cleanup() {
  await api('DELETE', `/api/sessions/${SESSION_ID}`);
}

process.on('SIGTERM', async () => { await cleanup(); process.exit(0); });
process.on('SIGINT', async () => { await cleanup(); process.exit(0); });

// ── MCP Tools ─────────────────────────────────────────────────

const mcp = new McpServer({ name: 'claude-mindmap', version: '1.0.0' });

mcp.tool(
  'mindmap_init',
  'Initialize a new mind map session with a root topic. Call this at the start of any complex task to begin visualizing your reasoning. Resets any existing map.',
  {
    title: z.string().describe('Central topic or task description'),
    model: z.string().optional().describe('Model name currently in use (e.g. claude-sonnet-4-6)'),
    input_tokens: z.coerce.number().optional().describe('Estimated input token budget'),
    output_tokens: z.coerce.number().optional().describe('Estimated output token budget')
  },
  async ({ title, model, input_tokens, output_tokens }) => {
    await api('POST', `/api/sessions/${SESSION_ID}/init`, { title, model, input_tokens, output_tokens });
    return { content: [{ type: 'text', text: `Mind map initialized: "${title}"\nView at ${BASE}` }] };
  }
);

mcp.tool(
  'mindmap_add_node',
  'Add a new node to the mind map. Use to represent thoughts, tool calls, observations, decisions, or final outputs as you reason through a task.',
  {
    id: z.string().describe('Unique node ID (e.g. "read-config", "analyze-1")'),
    parent_id: z.string().describe('Parent node ID. Use "root" for top-level branches'),
    label: z.string().describe('Short display label (keep under ~40 chars)'),
    detail: z.string().optional().describe('Longer description shown on hover'),
    type: z.enum(['thought', 'action', 'observation', 'decision', 'output']).describe(
      'Node type: thought=reasoning, action=tool use, observation=result/finding, decision=choice made, output=final result'
    ),
    input_tokens: z.coerce.number().optional().describe('Estimated input tokens consumed by this step'),
    output_tokens: z.coerce.number().optional().describe('Estimated output tokens generated by this step')
  },
  async ({ id, parent_id, label, detail, type, input_tokens, output_tokens }) => {
    await api('POST', `/api/sessions/${SESSION_ID}/nodes`, { id, parent_id, label, detail, type, input_tokens, output_tokens });
    return { content: [{ type: 'text', text: `Added "${label}" (${type})` }] };
  }
);

mcp.tool(
  'mindmap_update_node',
  'Update an existing mind map node. Use to mark steps complete/error, adjust token counts, or refine labels.',
  {
    id: z.string().describe('Node ID to update'),
    label: z.string().optional().describe('New label text'),
    status: z.enum(['active', 'complete', 'error']).optional().describe('New status'),
    detail: z.string().optional().describe('Updated detail text'),
    input_tokens: z.coerce.number().optional().describe('Updated input token count'),
    output_tokens: z.coerce.number().optional().describe('Updated output token count')
  },
  async ({ id, label, status, detail, input_tokens, output_tokens }) => {
    await api('PATCH', `/api/sessions/${SESSION_ID}/nodes/${id}`, { label, status, detail, input_tokens, output_tokens });
    return { content: [{ type: 'text', text: `Updated node "${id}" → ${status || 'modified'}` }] };
  }
);

mcp.tool(
  'mindmap_clear',
  'Clear the entire mind map to start fresh.',
  {},
  async () => {
    await api('POST', `/api/sessions/${SESSION_ID}/clear`);
    return { content: [{ type: 'text', text: 'Mind map cleared' }] };
  }
);

mcp.tool(
  'mindmap_open',
  'Open the mind map visualization in the default browser.',
  {},
  async () => {
    const cmd = process.platform === 'darwin' ? 'open' : process.platform === 'win32' ? 'start' : 'xdg-open';
    exec(`${cmd} ${BASE}`);
    return { content: [{ type: 'text', text: `Opened ${BASE}` }] };
  }
);

const transport = new StdioServerTransport();
await mcp.connect(transport);
